### ISSUE TITLE
JavaScript: Quiz Function

### ISSUE THREAD

**Issue by catherinelui2** [catherinelui2/Movia#6]
**on click for Start Quiz** 
- [x] ajax call
- [x] display questions
- [x] choices
- [x] score append

**Comment by GabrielleM45** [comment]
Got the ajax to call the quiz. Console.log to display results is in prelim.

Received suggestion from a learning assistant to do the following:

_leah.d.danielsAPP  7:15 PM
you may need a nested for loop. The outerloop would loop through the Questions and the innerloop would loop through the answer choices.__

**Comment by keldykins** [comment]
// need to figure out how to randomize questions and the correct/incorrect answer order using 'nested for loop'
 // make answers into buttons that when clicked will determine whether or not button click was correct or incorrect answer
 // save score data and dynamically append to page
